#App\view\resource\svg\schedule\moon-solid-white.svg

MOOM_SOLID = r'App\view\resources\svg\schedule\moon-solid-white.svg'
CLOCK_REGULAR = r'App\view\resources\svg\schedule\clock-regular-white.svg'
CALENDAR_REGULAR = r'App\view\resources\svg\schedule\calendar-regular.svg'
PEN = r'App\view\resources\svg\schedule\pen-svgrepo-com.svg'
PLUS = r'App\view\resources\svg\schedule\plus-solid.svg'
CHEVRON_RIGHT = r'App\view\resources\svg\schedule\chevron-right-solid.svg'
CHEVRON_LEFT = r'App\view\resources\svg\schedule\chevron-left-solid.svg'
ARROW_RIGHT = r'App\view\resources\svg\schedule\arrow-right-solid.svg'
ARROW_LEFT = r'App\view\resources\svg\schedule\arrow-left-solid.svg'
CHECK = r'App\view\resources\svg\schedule\check-solid.svg'
STOP_WATCH = r'App\view\resources\svg\schedule\stopwatch-solid.svg'
CARET_UP = r'App\view\resources\svg\schedule\caret-up-solid.svg'
CARET_DOWN = r'App\view\resources\svg\schedule\caret-down-solid.svg'
MAGNIFYING_GLASS = r'App\view\resources\svg\schedule\magnifying-glass-solid.svg'
SD_CARD = r'App\view\resources\svg\schedule\sd-card-solid.svg'
X_MARK = r'App\view\resources\svg\schedule\xmark-solid.svg'
UPLOAD = r'App\view\resources\svg\schedule\upload-solid.svg'
GEAR = r'App\view\resources\svg\schedule\gear-solid.svg'
TRASH = r'App\view\resources\svg\schedule\trash-solid.svg'
MOON_REGULAR = r'App\view\resources\svg\schedule\moon-regular.svg'
WINDOW_MAXIMIZE = r'App\view\resources\svg\schedule\window-maximize-regular.svg'
PAINT_ROLLER = r'App\view\resources\svg\schedule\paint-roller-solid.svg'
ROTATE_RIGHT = r'App\view\resources\svg\schedule\rotate-right-solid.svg'

DAWN = r'App\view\resources\svg\period\dawn.svg'
AFTERNOON = r'App\view\resources\svg\period\afternoon.svg'
MORNING = r'App\view\resources\svg\period\morning.svg'
NIGHT = r'App\view\resources\svg\period\night.svg'

BED = r'App\view\resources\svg\others\bed-solid.svg'
BOOK_BIBLE = r'App\view\resources\svg\others\book-bible-solid.svg'
BOOK = r'App\view\resources\svg\others\book-svgrepo-com.svg'
CART = r'App\view\resources\svg\others\cart-shopping-solid.svg'
CROSS = r'App\view\resources\svg\others\cross-solid.svg'
DUMBBELL = r'App\view\resources\svg\others\dumbbell-solid.svg'
FOOD_DINNER = r'App\view\resources\svg\others\food-dinner-svgrepo-com.svg'
SLEEP_MOON = r'App\view\resources\svg\others\sleep-moon-svgrepo-com.svg'
UNTENSILS = r'App\view\resources\svg\others\utensils-solid.svg'
WORKOUT = r'App\view\resources\svg\others\workout-svgrepo-com.svg'

BAN = r'App\view\resources\svg\priority\ban-solid.svg'
USER = r'App\view\resources\svg\priority\user-solid.svg'